
server:
  port: 8082

dubbo:
  application:
    name: dream-user
  registry:
    protocol: zookeeper
    address: 192.168.1.105:2181

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rsd?serverTimeZone=UTC
    username: root
    password: 123