server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rsd?serverTimeZone=UTC
    username: root
    password: 123


dubbo:
  application:
    name: dshop-user-service # 应用名称
  registry: # 注册中心
    address: 192.168.1.106:2181
    protocol: zookeeper
  protocol:
    port: 28800
